server:
  port: 8080

spring:
  application:
      name: sidecar-node

sidecar:
  home-page-uri: http://node-app-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/
  health-uri: http://node-app-lab-dekra.e4ff.pro-eu-west-1.openshiftapps.com/health
